/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import oshi.*;

/**
 *
 * @author CCIPRESSO
 */
public class Monitoring extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public Monitoring() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        sairPC = new javax.swing.JButton();
        cpuPC = new javax.swing.JTextField();
        diskPC = new javax.swing.JTextField();
        diskPC1 = new javax.swing.JTextField();
        diskPC2 = new javax.swing.JTextField();
        cpuPC1 = new javax.swing.JTextField();
        cpuPC2 = new javax.swing.JTextField();
        cpuPC3 = new javax.swing.JTextField();
        cpuPC4 = new javax.swing.JTextField();
        cpuPC5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cpuPC10 = new javax.swing.JTextField();
        cpuPC7 = new javax.swing.JTextField();
        cpuPC8 = new javax.swing.JTextField();
        cpuPC11 = new javax.swing.JTextField();
        cpuPC12 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelSmartMonkeyPC = new javax.swing.JLabel();
        labelMonitoramentoPC = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sairPC1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        sairPC.setBackground(new java.awt.Color(0, 153, 153));
        sairPC.setForeground(new java.awt.Color(255, 255, 255));
        sairPC.setText("Sair");
        sairPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairPCActionPerformed(evt);
            }
        });

        cpuPC.setEditable(false);
        cpuPC.setBackground(new java.awt.Color(0, 153, 153));
        cpuPC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cpuPC.setForeground(new java.awt.Color(255, 255, 255));
        cpuPC.setText("CPU");

        diskPC.setEditable(false);
        diskPC.setBackground(new java.awt.Color(0, 153, 153));
        diskPC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        diskPC.setForeground(new java.awt.Color(255, 255, 255));
        diskPC.setText("Disk");

        diskPC1.setEditable(false);
        diskPC1.setBackground(new java.awt.Color(0, 153, 153));
        diskPC1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        diskPC1.setForeground(new java.awt.Color(255, 255, 255));
        diskPC1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diskPC1.setText("SO");
        diskPC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskPC1ActionPerformed(evt);
            }
        });

        diskPC2.setEditable(false);
        diskPC2.setBackground(new java.awt.Color(0, 153, 153));
        diskPC2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        diskPC2.setForeground(new java.awt.Color(255, 255, 255));
        diskPC2.setText("RAM");
        diskPC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskPC2ActionPerformed(evt);
            }
        });

        cpuPC1.setEditable(false);
        cpuPC1.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cpuPC1.setText("Win 10, 64bits");

        cpuPC2.setEditable(false);
        cpuPC2.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cpuPC2.setText("45% em uso");

        cpuPC3.setEditable(false);
        cpuPC3.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cpuPC3.setText("50% em uso");
        cpuPC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuPC3ActionPerformed(evt);
            }
        });

        cpuPC4.setEditable(false);
        cpuPC4.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cpuPC4.setText("Intel i5 5271");
        cpuPC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuPC4ActionPerformed(evt);
            }
        });

        cpuPC5.setEditable(false);
        cpuPC5.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cpuPC5.setText("60% em uso"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Processos");

        cpuPC10.setEditable(false);
        cpuPC10.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cpuPC10.setText("SSD Kingston");
        cpuPC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuPC10ActionPerformed(evt);
            }
        });

        cpuPC7.setEditable(false);
        cpuPC7.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cpuPC7.setText("1,2 GHZ"); // NOI18N

        cpuPC8.setEditable(false);
        cpuPC8.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cpuPC8.setText("120/240 GB");
        cpuPC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuPC8ActionPerformed(evt);
            }
        });

        cpuPC11.setEditable(false);
        cpuPC11.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cpuPC11.setText("7,2/16 GB");

        cpuPC12.setEditable(false);
        cpuPC12.setBackground(new java.awt.Color(153, 153, 153));
        cpuPC12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cpuPC12.setText("Kingston");
        cpuPC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuPC12ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("Google Chrome - 20% ");

        jLabel3.setText("Visual Studio - 10%");

        jLabel4.setText("Win Explorer - 3%");

        jLabel5.setText("Antivirus - 2%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        labelSmartMonkeyPC.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        labelSmartMonkeyPC.setForeground(new java.awt.Color(255, 255, 255));
        labelSmartMonkeyPC.setText("Smart Monkey");

        labelMonitoramentoPC.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        labelMonitoramentoPC.setForeground(new java.awt.Color(255, 255, 255));
        labelMonitoramentoPC.setText("Monitoramento - Servidor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(labelMonitoramentoPC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSmartMonkeyPC)
                .addGap(261, 261, 261))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelSmartMonkeyPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMonitoramentoPC)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sairPC)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cpuPC4)
                    .addComponent(diskPC)
                    .addComponent(cpuPC)
                    .addComponent(cpuPC10)
                    .addComponent(diskPC1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cpuPC3)
                        .addComponent(cpuPC8)
                        .addComponent(cpuPC1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpuPC5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpuPC7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(diskPC2)
                            .addComponent(cpuPC12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cpuPC2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(cpuPC11, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpuPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diskPC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpuPC7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPC11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuPC12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sairPC)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diskPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpuPC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpuPC8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpuPC10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diskPC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpuPC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Monitoramento", jPanel1);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Equipe Smart Monkey composta por:");

        jLabel7.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Allan Tavares");

        jLabel8.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Caio Cipresso");

        jLabel9.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Juliana Oliveira");

        jLabel10.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Visite nosso site: www.smartmonkey.com.br");

        jLabel11.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tiago Pedroso");

        sairPC1.setText("Sair");
        sairPC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairPC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel11)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 124, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(sairPC1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(64, 64, 64))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(75, 75, 75)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(50, 50, 50)
                .addComponent(sairPC1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sobre nós", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpuPC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuPC12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpuPC12ActionPerformed

    private void cpuPC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuPC8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpuPC8ActionPerformed

    private void cpuPC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuPC10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpuPC10ActionPerformed

    private void cpuPC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuPC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpuPC4ActionPerformed

    private void cpuPC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuPC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpuPC3ActionPerformed

    private void diskPC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskPC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskPC2ActionPerformed

    private void diskPC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskPC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskPC1ActionPerformed

    private void sairPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairPCActionPerformed
        dispose();
    }//GEN-LAST:event_sairPCActionPerformed

    private void sairPC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairPC1ActionPerformed
        dispose();
    }//GEN-LAST:event_sairPC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitoring().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpuPC;
    private javax.swing.JTextField cpuPC1;
    private javax.swing.JTextField cpuPC10;
    private javax.swing.JTextField cpuPC11;
    private javax.swing.JTextField cpuPC12;
    private javax.swing.JTextField cpuPC2;
    private javax.swing.JTextField cpuPC3;
    private javax.swing.JTextField cpuPC4;
    private javax.swing.JTextField cpuPC5;
    private javax.swing.JTextField cpuPC7;
    private javax.swing.JTextField cpuPC8;
    private javax.swing.JTextField diskPC;
    private javax.swing.JTextField diskPC1;
    private javax.swing.JTextField diskPC2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelMonitoramentoPC;
    private javax.swing.JLabel labelSmartMonkeyPC;
    private javax.swing.JButton sairPC;
    private javax.swing.JButton sairPC1;
    // End of variables declaration//GEN-END:variables
}
